#!/usr/bin/perl

package eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsRequestType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. SetSellingManagerFeedbackOptionsRequestType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsRequestType

=head1 DESCRIPTION

Enables Selling Manager subscribers to store standard feedback comments that can 
be left for their buyers. Selling Manager Pro subscribers can also specify what 
events, if any, will trigger an automated feedback to buyers.



=head1 SYNOPSIS

=cut


=head1 INHERITANCE

eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsRequestType inherits from the L<eBay::API::XML::RequestDataType> class

=cut

use eBay::API::XML::RequestDataType;
our @ISA = ("eBay::API::XML::RequestDataType");

use eBay::API::XML::DataType::FeedbackCommentArrayType;
use eBay::API::XML::DataType::Enum::AutomatedLeaveFeedbackEventCodeType;


my @gaProperties = ( [ 'AutomatedLeaveFeedbackEvent', 'ns:AutomatedLeaveFeedbackEventCodeType', ''
	     ,'eBay::API::XML::DataType::Enum::AutomatedLeaveFeedbackEventCodeType', '' ]
	, [ 'StoredComments', 'ns:FeedbackCommentArrayType', ''
	     ,'eBay::API::XML::DataType::FeedbackCommentArrayType', '1' ]
                    );
push @gaProperties, @{eBay::API::XML::RequestDataType::getPropertiesList()};

my @gaAttributes = ( 
                    );
push @gaAttributes, @{eBay::API::XML::RequestDataType::getAttributesList()};

=head1 Subroutines:

=cut

sub new {
  my $classname = shift;
  my %args = @_;
  my $self = $classname->SUPER::new(%args);
  return $self;
}

sub isScalar {
   return 0; 
}



=head2 setAutomatedLeaveFeedbackEvent()

Specifies the event that will trigger automated feedback to the buyer. 
Applies to Selling Manager Pro subscribers only.

  RequiredInput: No
#    Argument: 'ns:AutomatedLeaveFeedbackEventCodeType'

=cut

sub setAutomatedLeaveFeedbackEvent {
  my $self = shift;
  $self->{'AutomatedLeaveFeedbackEvent'} = shift
}

=head2 getAutomatedLeaveFeedbackEvent()

#    Returns: 'ns:AutomatedLeaveFeedbackEventCodeType'

=cut

sub getAutomatedLeaveFeedbackEvent {
  my $self = shift;
  return $self->{'AutomatedLeaveFeedbackEvent'};
}


=head2 setStoredComments()

Contains a set of comments from which one can be selected to leave 
feedback for a buyer. If automated feedback is used, a comment is 
selected from the set randomly. Automated feedback applies to Selling 
Manager Pro subscribers only. Stored comments cannot be replaced or 
edited individually. Submitting a stored comments array replaces all 
existing stored comments.
<br>

  RequiredInput: No
#    Argument: 'ns:FeedbackCommentArrayType'

=cut

sub setStoredComments {
  my $self = shift;
  $self->{'StoredComments'} = shift
}

=head2 getStoredComments()

#    Returns: 'ns:FeedbackCommentArrayType'

=cut

sub getStoredComments {
  my $self = shift;
  return $self->_getDataTypeInstance( 'StoredComments'
		,'eBay::API::XML::DataType::FeedbackCommentArrayType');
}





##  Attribute and Property lists
sub getPropertiesList {
   my $self = shift;
   return \@gaProperties;
}

sub getAttributesList {
   my $self = shift;
   return \@gaAttributes;
}



1;   
