#!/usr/bin/perl

package eBay::API::XML::Release;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. Release.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::Release

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



use constant RELEASE_NUMBER => '583';
use constant RELEASE_TYPE   => 'public';



1;   
