#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::AutomatedLeaveFeedbackEventCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. AutomatedLeaveFeedbackEventCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::AutomatedLeaveFeedbackEventCodeType

=head1 DESCRIPTION

Events that will trigger an automated feedback to a buyer. Applies to Selling Manager Pro users.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 PositiveFeedbackReceived

Leave feedback automatically when you receive positive feedback.



=cut


use constant PositiveFeedbackReceived => scalar('PositiveFeedbackReceived');


=head2 PaymentReceived

Leave feedback automatically when you receive payment.



=cut


use constant PaymentReceived => scalar('PaymentReceived');


=head2 None

Do not leave feedback automatically.



=cut


use constant None => scalar('None');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
