#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::BalanceCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. BalanceCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::BalanceCodeType

=head1 DESCRIPTION

This code identifies the types of balances in an account, e.g., a PayPal account.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Other

(out) Custom Code.



=cut


use constant Other => scalar('Other');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
