#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::InventoryTrackingMethodCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. InventoryTrackingMethodCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::InventoryTrackingMethodCodeType

=head1 DESCRIPTION

This is to define the Item Listing type i.e. by item id or sku id.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 ItemID

For Listings with ItemId.



=cut


use constant ItemID => scalar('ItemID');


=head2 SKU

For Listings with SKU Id.



=cut


use constant SKU => scalar('SKU');


=head2 CustomCode

Reserved for internal or future use



=cut


use constant CustomCode => scalar('CustomCode');







1;   
