#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::InvocationStatusType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. InvocationStatusType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::InvocationStatusType

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 InProgress

=cut


use constant InProgress => scalar('InProgress');


=head2 Success

=cut


use constant Success => scalar('Success');


=head2 Failure

=cut


use constant Failure => scalar('Failure');


=head2 CustomCode

=cut


use constant CustomCode => scalar('CustomCode');







1;   
