#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::MailOptionsTypeCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. MailOptionsTypeCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::MailOptionsTypeCodeType

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 DoNotSendEmail

=cut


use constant DoNotSendEmail => scalar('DoNotSendEmail');


=head2 EmailCopyToSender

=cut


use constant EmailCopyToSender => scalar('EmailCopyToSender');


=head2 HideSenderEmailAddress

=cut


use constant HideSenderEmailAddress => scalar('HideSenderEmailAddress');


=head2 CustomCode

=cut


use constant CustomCode => scalar('CustomCode');







1;   
