#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::MeasurementSystemCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. MeasurementSystemCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::MeasurementSystemCodeType

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 English

English system of measurement.



=cut


use constant English => scalar('English');


=head2 Metric

Metric system of measurement.



=cut


use constant Metric => scalar('Metric');







1;   
