#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::ReturnsAcceptedOptionsCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. ReturnsAcceptedOptionsCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::ReturnsAcceptedOptionsCodeType

=head1 DESCRIPTION

Specified whether returns are accepted.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 ReturnsAccepted

The seller accepts returns, subject to other details 
specified in the policy.



=cut


use constant ReturnsAccepted => scalar('ReturnsAccepted');


=head2 ReturnsNotAccepted

The seller does not accept returns.



=cut


use constant ReturnsNotAccepted => scalar('ReturnsNotAccepted');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
