#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::ReturnsWithinOptionsCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. ReturnsWithinOptionsCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::ReturnsWithinOptionsCodeType

=head1 DESCRIPTION

The number of days within which the item can be returned.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Days_3

3 days



=cut


use constant Days_3 => scalar('Days_3');


=head2 Days_7

7 days



=cut


use constant Days_7 => scalar('Days_7');


=head2 Days_10

10 days



=cut


use constant Days_10 => scalar('Days_10');


=head2 Days_14

14 days



=cut


use constant Days_14 => scalar('Days_14');


=head2 Days_30

30 days



=cut


use constant Days_30 => scalar('Days_30');


=head2 Days_60

60 days



=cut


use constant Days_60 => scalar('Days_60');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
