#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::ShippingCostPaidByOptionsCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. ShippingCostPaidByOptionsCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::ShippingCostPaidByOptionsCodeType

=head1 DESCRIPTION

This specifies the party (Seller/Buyer) who is going to pay the return shipping cost.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Buyer

Buyer pays return shipping cost.



=cut


use constant Buyer => scalar('Buyer');


=head2 Seller

Seller pays return shipping cost.



=cut


use constant Seller => scalar('Seller');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
