#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::WarrantyDurationOptionsCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. WarrantyDurationOptionsCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::WarrantyDurationOptionsCodeType

=head1 DESCRIPTION

Specifies the various warranty durations being offered.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Months_1

1 month



=cut


use constant Months_1 => scalar('Months_1');


=head2 Months_3

3 months



=cut


use constant Months_3 => scalar('Months_3');


=head2 Months_6

6 months



=cut


use constant Months_6 => scalar('Months_6');


=head2 Years_1

1 year



=cut


use constant Years_1 => scalar('Years_1');


=head2 Years_2

2 years



=cut


use constant Years_2 => scalar('Years_2');


=head2 Years_3

3 years



=cut


use constant Years_3 => scalar('Years_3');


=head2 Years_MoreThan3

More than 3 years



=cut


use constant Years_MoreThan3 => scalar('Years_MoreThan3');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
