#!/usr/bin/perl

package eBay::API::XML::Call::SetSellingManagerFeedbackOptions;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. SetSellingManagerFeedbackOptions.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::Call::SetSellingManagerFeedbackOptions

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut


=head1 INHERITANCE

eBay::API::XML::Call::SetSellingManagerFeedbackOptions inherits from the L<eBay::API::XML::BaseCall> class

=cut

use eBay::API::XML::BaseCall;
our @ISA = ("eBay::API::XML::BaseCall");

use eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsRequestType;
use eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsResponseType;


=head1 Subroutines:

=cut

sub getApiCallName {
   return 'SetSellingManagerFeedbackOptions';
}
sub getRequestDataTypeFullPackage {
   return 'eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsRequestType';
}
sub getResponseDataTypeFullPackage {
   return 'eBay::API::XML::Call::SetSellingManagerFeedbackOptions::SetSellingManagerFeedbackOptionsResponseType';
}

#
# input properties
#

=head2 setAutomatedLeaveFeedbackEvent()

Specifies the event that will trigger automated feedback to the buyer. 
Applies to Selling Manager Pro subscribers only.

  RequiredInput: No
#    Argument: 'ns:AutomatedLeaveFeedbackEventCodeType'

=cut
       
sub setAutomatedLeaveFeedbackEvent {
   my $self   = shift;
   my $sAutomatedLeaveFeedbackEvent = shift;
   $self->getRequestDataType()->setAutomatedLeaveFeedbackEvent($sAutomatedLeaveFeedbackEvent);
}

=head2 setStoredComments()

Contains a set of comments from which one can be selected to leave 
feedback for a buyer. If automated feedback is used, a comment is 
selected from the set randomly. Automated feedback applies to Selling 
Manager Pro subscribers only. Stored comments cannot be replaced or 
edited individually. Submitting a stored comments array replaces all 
existing stored comments.
<br>

  RequiredInput: No
#    Argument: 'ns:FeedbackCommentArrayType'

=cut
       
sub setStoredComments {
   my $self   = shift;
   my $pStoredComments = shift;
   $self->getRequestDataType()->setStoredComments($pStoredComments);
}



#
# output properties
#





1;   
