#!/usr/bin/perl

package eBay::API::XML::DataType::LookupAttributeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. LookupAttributeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::LookupAttributeType

=head1 DESCRIPTION

An optional attribute that the seller wants to include in the listing.
Enables you to specify an attribute by name rather than by ID.
Only valid in Media categories (Books, DVD and Movies, Music, and Video Game categories).
Currently, only the Condition attribute is supported.



=head1 SYNOPSIS

=cut


=head1 INHERITANCE

eBay::API::XML::DataType::LookupAttributeType inherits from the L<eBay::API::XML::BaseDataType> class

=cut

use eBay::API::XML::BaseDataType;
our @ISA = ("eBay::API::XML::BaseDataType");



my @gaProperties = ( [ 'Name', 'xs:string', '', '', '' ]
	, [ 'Value', 'xs:string', '', '', '' ]
                    );
push @gaProperties, @{eBay::API::XML::BaseDataType::getPropertiesList()};

my @gaAttributes = ( 
                    );
push @gaAttributes, @{eBay::API::XML::BaseDataType::getAttributesList()};

=head1 Subroutines:

=cut

sub new {
  my $classname = shift;
  my %args = @_;
  my $self = $classname->SUPER::new(%args);
  return $self;
}

sub isScalar {
   return 0; 
}



=head2 setName()

The literal name of the attribute. Pass "Condition" (without quotes).
Not applicable to Half.com.

  Calls: AddItem
         GetItemRecommendations
         RelistItem
         VerifyAddItem
  RequiredInput: No

#    Argument: 'xs:string'

=cut

sub setName {
  my $self = shift;
  $self->{'Name'} = shift
}

=head2 getName()

#    Returns: 'xs:string'

=cut

sub getName {
  my $self = shift;
  return $self->{'Name'};
}


=head2 setValue()

The literal name of the attribute value. Pass "New" or "Used" (without quotes).
Not applicable to Half.com.<br>
<br>
<span class="tablenote"><b>Note</b>:
Currently, LookupAttribute does not recognize other values, and it assumes the attribute is Condition.
Do not attempt to specify other values for other attributes in the lookup attribute.
Even if a given site or category normally uses a variation like "New in box", 
you should still just specify "New" as the lookup attribute value. eBay translates the LookupAttribute value to the appropriate condition attribute in the 
listing's Item Specifics.<br>
<br>
Also, the new condition values for Media categories on the US site are not yet supported.
So, do not specify Brand New, Like New, Very Good, Good, or Acceptable in LookupAttribute.<br>
<br>
Once the value is translated to the correct condition attribute, 
the attribute ID and value ID are stored on the item. This means the condition is returned in 
AttributeSetArray in GetItem. It also means that if you revise a listing's attributes, 
you need to specify the condition attribute ID and value ID in AttributeSetArray to 
prevent them from being dropped from the listing.</span>

  Calls: AddItem
         GetItemRecommendations
         RelistItem
         VerifyAddItem
  RequiredInput: No

#    Argument: 'xs:string'

=cut

sub setValue {
  my $self = shift;
  $self->{'Value'} = shift
}

=head2 getValue()

#    Returns: 'xs:string'

=cut

sub getValue {
  my $self = shift;
  return $self->{'Value'};
}





##  Attribute and Property lists
sub getPropertiesList {
   my $self = shift;
   return \@gaProperties;
}

sub getAttributesList {
   my $self = shift;
   return \@gaAttributes;
}



1;   
