#!/usr/bin/perl

package eBay::API::XML::DataType::StoreOwnerExtendedListingDurationsType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. StoreOwnerExtendedListingDurationsType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::StoreOwnerExtendedListingDurationsType

=head1 DESCRIPTION

Defines the extended listing durations availabe to store owners.
If the field is present, the corresponding feature applies to the category.
The field is returned as an	empty element (e.g., a boolean value is not returned).
Applies to Fixed Price Listings as well as Store Inventory Format Listings.



=head1 SYNOPSIS

=cut


=head1 INHERITANCE

eBay::API::XML::DataType::StoreOwnerExtendedListingDurationsType inherits from the L<eBay::API::XML::BaseDataType> class

=cut

use eBay::API::XML::BaseDataType;
our @ISA = ("eBay::API::XML::BaseDataType");



my @gaProperties = ( [ 'Duration', 'xs:token', '1', '', '' ]
                    );
push @gaProperties, @{eBay::API::XML::BaseDataType::getPropertiesList()};

my @gaAttributes = ( 
                    );
push @gaAttributes, @{eBay::API::XML::BaseDataType::getAttributesList()};

=head1 Subroutines:

=cut

sub new {
  my $classname = shift;
  my %args = @_;
  my $self = $classname->SUPER::new(%args);
  return $self;
}

sub isScalar {
   return 0; 
}



=head2 setDuration()

Specifies the length of time an auction can be open, in days. The allowed durations
vary according to the type of listing. The value GTC means Good Til Canceled.

#    Argument: reference to an array  
                      of 'xs:token'

=cut

sub setDuration {
  my $self = shift;
  $self->{'Duration'} = 
		$self->convertArray_To_RefToArrayIfNeeded(@_);
}

=head2 getDuration()

  Calls: GetCategoryFeatures
  Returned: Conditionally
  Details: DetailLevel: ReturnAll

#    Returns: reference to an array  
                      of 'xs:token'

=cut

sub getDuration {
  my $self = shift;
  return $self->_getDataTypeArray('Duration');
}





##  Attribute and Property lists
sub getPropertiesList {
   my $self = shift;
   return \@gaProperties;
}

sub getAttributesList {
   my $self = shift;
   return \@gaAttributes;
}



1;   
