#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::DescriptionTemplateCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. DescriptionTemplateCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::DescriptionTemplateCodeType

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Layout

The template details establish how pictures are to be
positioned relative to the description text.



=cut


use constant Layout => scalar('Layout');


=head2 Theme

The template determines which eBay-provided theme (e.g.
Valentine's Day) is to be applied for presenting pictures
and description text.



=cut


use constant Theme => scalar('Theme');


=head2 CustomCode

Reserved for future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
