#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::DisputeRecordTypeCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. DisputeRecordTypeCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::DisputeRecordTypeCodeType

=head1 DESCRIPTION

Describes the type of dispute, either Unpaid Item or Item Not Received.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 UnpaidItem

(out) An Unpaid Item dispute.



=cut


use constant UnpaidItem => scalar('UnpaidItem');


=head2 ItemNotReceived

(out) An Item Not Received dispute.



=cut


use constant ItemNotReceived => scalar('ItemNotReceived');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
