#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::FeatureIDCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. FeatureIDCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 07/07/2008 17:42
# API Release Number: ... 571
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::FeatureIDCodeType

=head1 DESCRIPTION

Specifies the feature IDs for which you want information. If you do not specify a value, all feature IDs are returned.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 ListingDurations

(in) Returns information about the durations of listings you can use in a
given category.
<br><br>
<bold>Note:</bold> Durations for Local Market listings are not
supported by GetCategoryFeatures. Refer to the Local Market Listing
documentation in the
Web Services Guide for valid listing durations.



=cut


use constant ListingDurations => scalar('ListingDurations');


=head2 BestOfferEnabled

(in) Returns information about whether a category supports best offers.



=cut


use constant BestOfferEnabled => scalar('BestOfferEnabled');


=head2 DutchBINEnabled

(in) Returned if a site and category allow Buy It Now for Dutch auctions.



=cut


use constant DutchBINEnabled => scalar('DutchBINEnabled');


=head2 ShippingTermsRequired

(in) Returns information about whether a seller is required to
specify at least one domestic shipping
service and associated cost in order to list the item.



=cut


use constant ShippingTermsRequired => scalar('ShippingTermsRequired');


=head2 UserConsentRequired

(in) Returns information about whether a bidder must consent to the bid
by confirming that he or she read and agrees to the terms in eBay's privacy policy.



=cut


use constant UserConsentRequired => scalar('UserConsentRequired');


=head2 HomePageFeaturedEnabled

(in) Indicates whether or not it is possible to enhance a listing by putting
it into a rotation for display on a special area of the eBay home page.
Support for this feature varies by site. Item or feedback restrictions may apply.



=cut


use constant HomePageFeaturedEnabled => scalar('HomePageFeaturedEnabled');


=head2 AdFormatEnabled

(in) Indicates whether the category supports ad-format.



=cut


use constant AdFormatEnabled => scalar('AdFormatEnabled');


=head2 DigitalDeliveryEnabled

=cut


use constant DigitalDeliveryEnabled => scalar('DigitalDeliveryEnabled');


=head2 BestOfferCounterEnabled

(in) Returns information about whether a category supports counter-offers for Best Offers.



=cut


use constant BestOfferCounterEnabled => scalar('BestOfferCounterEnabled');


=head2 BestOfferAutoDeclineEnabled

(in) Returns information about whether a category supports auto-decline for Best Offers.



=cut


use constant BestOfferAutoDeclineEnabled => scalar('BestOfferAutoDeclineEnabled');


=head2 ProPack

(in) Returns information about ProPackBundle (a feature pack). Applies only to US and Canadian eBay motor vehicle sellers. Contains the Bold, Border, Featured and Highlight features.



=cut


use constant ProPack => scalar('ProPack');


=head2 BasicUpgradePack

(in) Not applicable to any site.
Formerly, Australia site (site ID 15, abbreviation AU) only, and
returned information about the BasicUpgradePack bundle (a feature pack),
which combined the features Gallery and Subtitle for a discounted price.



=cut


use constant BasicUpgradePack => scalar('BasicUpgradePack');


=head2 ValuePack

(in) Returns information about the ValuePack bundle (a feature pack),
which combines the features Gallery, Subtitle, and Listing Designer for a discounted price. Support for this feature varies by site and category.



=cut


use constant ValuePack => scalar('ValuePack');


=head2 ProPackPlus

(in) Returns information about the ProPackPlus bundle (a feature pack),
which combines the features BoldTitle, Border, Highlight, Featured, and Gallery for a discounted price. Support for this feature varies by site and category.



=cut


use constant ProPackPlus => scalar('ProPackPlus');


=head2 LocalMarketSpecialitySubscription

(in) Returns information about whether a category supports Local Market listings for sellers subscribed to Local Market for Specialty Vehicles.



=cut


use constant LocalMarketSpecialitySubscription => scalar('LocalMarketSpecialitySubscription');


=head2 LocalMarketRegularSubscription

(in) Returns information about whether a category supports Local Market listings for sellers subscribed to Local Market for Vehicles.



=cut


use constant LocalMarketRegularSubscription => scalar('LocalMarketRegularSubscription');


=head2 LocalMarketPremiumSubscription

(in) Returns information about whether a category supports Local Market listings for sellers with a premium Local Market subscription.



=cut


use constant LocalMarketPremiumSubscription => scalar('LocalMarketPremiumSubscription');


=head2 LocalMarketNonSubscription

(in) Returns information about whether a category supports Local Market listings for sellers without a Local Market subscription.



=cut


use constant LocalMarketNonSubscription => scalar('LocalMarketNonSubscription');


=head2 ExpressEnabled

(in) Returns information about whether a category is eligible for eBay Express.



=cut


use constant ExpressEnabled => scalar('ExpressEnabled');


=head2 ExpressPicturesRequired

(in) Returns information about whether a category requires pictures to be listed on Express.



=cut


use constant ExpressPicturesRequired => scalar('ExpressPicturesRequired');


=head2 ExpressConditionRequired

(in) Returns information about whether a category requires item condition to be listed on Express.



=cut


use constant ExpressConditionRequired => scalar('ExpressConditionRequired');


=head2 SellerContactDetailsEnabled

(in) Returns information about whether this category allows seller-level
contact information for Classified Ad listings.



=cut


use constant SellerContactDetailsEnabled => scalar('SellerContactDetailsEnabled');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');


=head2 MinimumReservePrice

(in) Returns information about whether a category supports Minimum Reserve Price.



=cut


use constant MinimumReservePrice => scalar('MinimumReservePrice');


=head2 TransactionConfirmationRequestEnabled

(in) Returns information about whether a category supports the Transaction
Confirmation Request (TCR) feature.



=cut


use constant TransactionConfirmationRequestEnabled => scalar('TransactionConfirmationRequestEnabled');


=head2 StoreInventoryEnabled

(in) Indicates whether the category supports Store Inventory Format.



=cut


use constant StoreInventoryEnabled => scalar('StoreInventoryEnabled');


=head2 LocalListingDistances

(in) Returns information about the supported local listing distances for different levels of Local Market subscription.



=cut


use constant LocalListingDistances => scalar('LocalListingDistances');


=head2 SkypeMeTransactionalEnabled

(in) Returns information about whether a category supports the addition of
Skype buttons to listings for transactional formats (e.g., the Chinese auction format).



=cut


use constant SkypeMeTransactionalEnabled => scalar('SkypeMeTransactionalEnabled');


=head2 SkypeMeNonTransactionalEnabled

(in) Returns information about whether a category supports the addition of Skype buttons to listings for non-transactional formats (e.g., the advertisement format).



=cut


use constant SkypeMeNonTransactionalEnabled => scalar('SkypeMeNonTransactionalEnabled');


=head2 ClassifiedAdPaymentMethodEnabled

(in) Returns information about whether the payment method is displayed
to the user for Classified Ad listings in this category.
Even if payment method is displayed, checkout may or may not be enabled.



=cut


use constant ClassifiedAdPaymentMethodEnabled => scalar('ClassifiedAdPaymentMethodEnabled');


=head2 ClassifiedAdShippingMethodEnabled

(in) Returns information about whether shipping options are available for
Classified Ad listings in this category.



=cut


use constant ClassifiedAdShippingMethodEnabled => scalar('ClassifiedAdShippingMethodEnabled');


=head2 ClassifiedAdBestOfferEnabled

(in) Returns information about whether Best Offer is enabled for Classified
Ad listings.



=cut


use constant ClassifiedAdBestOfferEnabled => scalar('ClassifiedAdBestOfferEnabled');


=head2 ClassifiedAdCounterOfferEnabled

(in) Returns information about whether counter offers are allowed on
Classified Ad listings for this category.
Returned only if this category overrides the site default.



=cut


use constant ClassifiedAdCounterOfferEnabled => scalar('ClassifiedAdCounterOfferEnabled');


=head2 ClassifiedAdAutoDeclineEnabled

(in) Returns information about whether automatic decline for best
offers are allowed for Classified Ad listings in this category.
Returned only if this category overrides the site default.



=cut


use constant ClassifiedAdAutoDeclineEnabled => scalar('ClassifiedAdAutoDeclineEnabled');


=head2 ClassifiedAdContactByEmailEnabled

(in) Returns information about whether this category supports including an email address in the seller's contact information.



=cut


use constant ClassifiedAdContactByEmailEnabled => scalar('ClassifiedAdContactByEmailEnabled');


=head2 ClassifiedAdContactByPhoneEnabled

(in) Returns information about whether this category supports including a telephone number in the seller's contact information.



=cut


use constant ClassifiedAdContactByPhoneEnabled => scalar('ClassifiedAdContactByPhoneEnabled');


=head2 SafePaymentRequired

(in) Returns information about whether a category requires
a safe payment method. If a seller has a 'SafePaymentExempt'
status (see GetUser), they are exempt from the requirement to offer at least
one safe payment method when listing an item.



=cut


use constant SafePaymentRequired => scalar('SafePaymentRequired');


=head2 MaximumBestOffersAllowed

(in) Returns information about the number of Best Offers
allowed for a non-Ad-Format-Listings buyer.



=cut


use constant MaximumBestOffersAllowed => scalar('MaximumBestOffersAllowed');


=head2 ClassifiedAdMaximumBestOffersAllowed

(in) Returns information about the number of Best Offers
allowed for a Classified-Ad-Format-Listings buyer.



=cut


use constant ClassifiedAdMaximumBestOffersAllowed => scalar('ClassifiedAdMaximumBestOffersAllowed');


=head2 ClassifiedAdContactByEmailAvailable

(in) Returns information about whether this category supports including an email address in the seller's contact information for classified-ad listings.



=cut


use constant ClassifiedAdContactByEmailAvailable => scalar('ClassifiedAdContactByEmailAvailable');


=head2 ClassifiedAdPayPerLeadEnabled

(in) Returns information about whether a category supports pay-per-lead listings.



=cut


use constant ClassifiedAdPayPerLeadEnabled => scalar('ClassifiedAdPayPerLeadEnabled');


=head2 ItemSpecificsEnabled

(in) Returns information about whether categories support
custom Item Specifics.



=cut


use constant ItemSpecificsEnabled => scalar('ItemSpecificsEnabled');


=head2 PaisaPayFullEscrowEnabled

(in) Returns information about whether PaisaPayEscrow payment method is enabled.



=cut


use constant PaisaPayFullEscrowEnabled => scalar('PaisaPayFullEscrowEnabled');


=head2 ClassifiedAdAutoAcceptEnabled

(in) Returns information about whether auto-accept for Best
Offers is allowed for Classified Ad listings in this category.



=cut


use constant ClassifiedAdAutoAcceptEnabled => scalar('ClassifiedAdAutoAcceptEnabled');


=head2 BestOfferAutoAcceptEnabled

(in) Returns information about whether auto-accept for Best
Offers is allowed for listings in this category.



=cut


use constant BestOfferAutoAcceptEnabled => scalar('BestOfferAutoAcceptEnabled');


=head2 CrossBorderTradeEnabled

(in) Returns information about whether a category allows listings to
be displayed in another site's default search results.



=cut


use constant CrossBorderTradeEnabled => scalar('CrossBorderTradeEnabled');


=head2 PayPalBuyerProtectionEnabled

(in) On the Australia site, returns information about whether a category allows PayPal buyer protection.



=cut


use constant PayPalBuyerProtectionEnabled => scalar('PayPalBuyerProtectionEnabled');


=head2 BuyerGuaranteeEnabled

(in) On the Australia site, returns information about whether a category allows PayPal buyer protection.



=cut


use constant BuyerGuaranteeEnabled => scalar('BuyerGuaranteeEnabled');


=head2 INEscrowWorkflowTimeline

(in) On the India site, returns information about the escrow workflow version applicable to the given category, if the category supports PaisaPayFullEscrow.



=cut


use constant INEscrowWorkflowTimeline => scalar('INEscrowWorkflowTimeline');


=head2 CombinedFixedPriceTreatment

On the Italy site, returns information about whether a category allows combined fixed price treatment of the following two listing types:
Store Inventory Format and Basic Fixed Price.



=cut


use constant CombinedFixedPriceTreatment => scalar('CombinedFixedPriceTreatment');


=head2 GalleryFeaturedDurations

On the Italy Site, returns information about whether a category allows durations for "Gallery Featured".



=cut


use constant GalleryFeaturedDurations => scalar('GalleryFeaturedDurations');


=head2 PayPalRequired

(in) Returns information about whether listings in a category
require PayPal as a payment method.



=cut


use constant PayPalRequired => scalar('PayPalRequired');


=head2 eBayMotorsProAdFormatEnabled

(in) Indicates whether the category supports ad-format. Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProAdFormatEnabled => scalar('eBayMotorsProAdFormatEnabled');


=head2 eBayMotorsProContactByPhoneEnabled

(in) Returns information about whether the telephone can be a contact method
for the category. Added for eBay Motorss Pro users.



=cut


use constant eBayMotorsProContactByPhoneEnabled => scalar('eBayMotorsProContactByPhoneEnabled');


=head2 eBayMotorsProContactByAddressEnabled

(in) Returns information about whether this category supports including an address in the seller's contact information.
Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProContactByAddressEnabled => scalar('eBayMotorsProContactByAddressEnabled');


=head2 eBayMotorsProCompanyNameEnabled

(in) Returns information about whether this category supports including a company name in the seller's contact information. Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProCompanyNameEnabled => scalar('eBayMotorsProCompanyNameEnabled');


=head2 eBayMotorsProContactByEmailEnabled

(in) Returns information about whether this category supports including an email address in the seller's contact information. Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProContactByEmailEnabled => scalar('eBayMotorsProContactByEmailEnabled');


=head2 eBayMotorsProBestOfferEnabled

(in) Returns information about whether a category supports Best Offers.
Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProBestOfferEnabled => scalar('eBayMotorsProBestOfferEnabled');


=head2 eBayMotorsProAutoAcceptEnabled

(in) Returns information about whether a category supports auto accept.
Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProAutoAcceptEnabled => scalar('eBayMotorsProAutoAcceptEnabled');


=head2 eBayMotorsProAutoDeclineEnabled

(in) Returns information about whether a category supports auto decline.
Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProAutoDeclineEnabled => scalar('eBayMotorsProAutoDeclineEnabled');


=head2 eBayMotorsProPaymentMethodCheckOutEnabled

(in) Returns information about whether a category supports payment method checkout.
Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProPaymentMethodCheckOutEnabled => scalar('eBayMotorsProPaymentMethodCheckOutEnabled');


=head2 eBayMotorsProShippingMethodEnabled

(in) Returns information about whether shipping options are available in the category.
Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProShippingMethodEnabled => scalar('eBayMotorsProShippingMethodEnabled');


=head2 eBayMotorsProCounterOfferEnabled

(in) Returns information about whether counter offers are allowed for this category.
Returned only if this category overrides the site default. Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProCounterOfferEnabled => scalar('eBayMotorsProCounterOfferEnabled');


=head2 eBayMotorsProSellerContactDetailsEnabled

(in) Returns information about whether this category allows seller-level
contact information for Classified Ad listings. Added for eBay Motors Pro users.



=cut


use constant eBayMotorsProSellerContactDetailsEnabled => scalar('eBayMotorsProSellerContactDetailsEnabled');


=head2 LocalMarketAdFormatEnabled

(in) Indicates whether the category supports ad-format. Added for Local Market users.



=cut


use constant LocalMarketAdFormatEnabled => scalar('LocalMarketAdFormatEnabled');


=head2 LocalMarketContactByPhoneEnabled

(in) Returns information about whether this category supports including a telephone number in the seller's contact information. Added for Local Market users.



=cut


use constant LocalMarketContactByPhoneEnabled => scalar('LocalMarketContactByPhoneEnabled');


=head2 LocalMarketContactByAddressEnabled

(in) Returns information about whether this category supports including an address in the seller's contact information. Added for Local Market users.



=cut


use constant LocalMarketContactByAddressEnabled => scalar('LocalMarketContactByAddressEnabled');


=head2 LocalMarketCompanyNameEnabled

(in) Returns information about whether this category supports including a company name in the seller's contact information. Added for Local Market users.



=cut


use constant LocalMarketCompanyNameEnabled => scalar('LocalMarketCompanyNameEnabled');


=head2 LocalMarketContactByEmailEnabled

(in) Returns information about whether this category supports including an email address in the seller's contact information. Added for Local Market users.



=cut


use constant LocalMarketContactByEmailEnabled => scalar('LocalMarketContactByEmailEnabled');


=head2 LocalMarketBestOfferEnabled

(in) Returns information about whether a category supports Best Offers for Classified Ad listings.
Added for Local Market users.



=cut


use constant LocalMarketBestOfferEnabled => scalar('LocalMarketBestOfferEnabled');


=head2 LocalMarketAutoAcceptEnabled

(in) Returns information about whether a category supports auto accept.
Added for Local Market users.



=cut


use constant LocalMarketAutoAcceptEnabled => scalar('LocalMarketAutoAcceptEnabled');


=head2 LocalMarketAutoDeclineEnabled

(in) Returns information about whether a category supports auto decline.
Added for Local Market users.



=cut


use constant LocalMarketAutoDeclineEnabled => scalar('LocalMarketAutoDeclineEnabled');


=head2 LocalMarketPaymentMethodCheckOutEnabled

(in) Returns information about whether a category supports payment method checkout.
Added for Local Market users.



=cut


use constant LocalMarketPaymentMethodCheckOutEnabled => scalar('LocalMarketPaymentMethodCheckOutEnabled');


=head2 LocalMarketShippingMethodEnabled

(in) Returns information about whether shipping options are available for
listings in the category. Added for Local Market users.



=cut


use constant LocalMarketShippingMethodEnabled => scalar('LocalMarketShippingMethodEnabled');


=head2 LocalMarketCounterOfferEnabled

(in) Returns information about whether counter offers are allowed for this category .
Returned only if this category overrides the site default. Added for Local Market users.



=cut


use constant LocalMarketCounterOfferEnabled => scalar('LocalMarketCounterOfferEnabled');


=head2 LocalMarketSellerContactDetailsEnabled

(in) Returns information about whether this category allows seller-level
contact information. Added for Local Market users.



=cut


use constant LocalMarketSellerContactDetailsEnabled => scalar('LocalMarketSellerContactDetailsEnabled');


=head2 ClassifiedAdContactByAddressEnabled

(in) Returns information about whether the contact by address is enabled.
Added for For Sale By Owner.



=cut


use constant ClassifiedAdContactByAddressEnabled => scalar('ClassifiedAdContactByAddressEnabled');


=head2 ClassifiedAdCompanyNameEnabled

(in) Returns information about whether this category supports including a company name in the seller's contact information. Added for For Sale By Owmer.



=cut


use constant ClassifiedAdCompanyNameEnabled => scalar('ClassifiedAdCompanyNameEnabled');


=head2 SpecialitySubscription

(in) Returns information about whether a category supports Local Market listings for sellers
subscribed to Local Market for Specialty Vehicles. Added for subscription.



=cut


use constant SpecialitySubscription => scalar('SpecialitySubscription');


=head2 RegularSubscription

(in) Returns information about whether a category supports Local Market listings for sellers
subscribed to Local Market for Vehicles. Added for subscription.



=cut


use constant RegularSubscription => scalar('RegularSubscription');


=head2 PremiumSubscription

(in) Returns information about whether a category supports Local Market listings for sellers
with a premium Local Market subscription. Added for subscription.



=cut


use constant PremiumSubscription => scalar('PremiumSubscription');


=head2 NonSubscription

(in) Returns information about whether a category supports Local Market listings for sellers without a
Local Market subscription. Added for subscription.



=cut


use constant NonSubscription => scalar('NonSubscription');







1;   
