#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::NotificationPayloadTypeCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. NotificationPayloadTypeCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::NotificationPayloadTypeCodeType

=head1 DESCRIPTION

The schema options for Platform Notifications.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 eBLSchemaSOAP

New Schema format (used by the new schema XML API and SOAP API).



=cut


use constant eBLSchemaSOAP => scalar('eBLSchemaSOAP');


=head2 CustomCode

Reserved for internal or future use



=cut


use constant CustomCode => scalar('CustomCode');







1;   
