#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::OrderRoleCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. OrderRoleCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::OrderRoleCodeType

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Buyer

=cut


use constant Buyer => scalar('Buyer');


=head2 Seller

=cut


use constant Seller => scalar('Seller');


=head2 CustomCode

=cut


use constant CustomCode => scalar('CustomCode');







1;   
