#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::SelectionModeCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. SelectionModeCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 09/23/2008 13:56
# API Release Number: ... 583
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::SelectionModeCodeType

=head1 DESCRIPTION

This is automatic or manual depending on selection.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Automatic

Automatic criteria.



=cut


use constant Automatic => scalar('Automatic');


=head2 Manual

Manual criteria.



=cut


use constant Manual => scalar('Manual');


=head2 CustomCode

Reserved for future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
