#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::ShipmentStatusCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. ShipmentStatusCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
# Last Generated: ....... 07/07/2008 17:42
# API Release Number: ... 571
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::ShipmentStatusCodeType

=head1 DESCRIPTION



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 Active

=cut


use constant Active => scalar('Active');


=head2 Canceled

=cut


use constant Canceled => scalar('Canceled');


=head2 CustomCode

=cut


use constant CustomCode => scalar('CustomCode');







1;   
