#!/usr/bin/perl

package eBay::API::XML::DataType::Enum::WarrantyOfferedCodeType;

use strict;
use warnings;  

##########################################################################
#
# Module: ............... <user defined location>eBay/API/XML
# File: ................. WarrantyOfferedCodeType.pm
# Generated by: ......... genEBayApiDataTypes.pl
#
##########################################################################  

=head1 NAME

eBay::API::XML::DataType::Enum::WarrantyOfferedCodeType

=head1 DESCRIPTION

Specifies that the warranty is offered for the item by the seller.



=head1 SYNOPSIS

=cut



=head1 Enums:

=cut


=head2 WarrantyOffered

A warranty is offered for the item.



=cut


use constant WarrantyOffered => scalar('WarrantyOffered');


=head2 CustomCode

(out) Reserved for internal or future use.



=cut


use constant CustomCode => scalar('CustomCode');







1;   
